leftnav:
- identifier: ac0d541b-144d-484f-9611-15a83f0b063f
  name: Menu for Course
  url: /lists/r2
  weight: 10
- identifier: 8dd69d55-d392-4ae4-9605-4a5510d3e404
  name: Videos
  url: /lists/videos
  weight: 20
